name: Deploy to GitHub Pages

on:
  # Runs on push to the main branch
  push:
    branches:
      - main

  # Allows to manually trigger the workflow from GitHub Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Copy files to public folder
        run: |
          mkdir -p public
          cp -r json/* public/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
