name: Fetch Data and Commit JSON ##

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'

jobs:
  fetch_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install dotenv

    - name: Run Fetch Script
      run: node fetchData.js
      env:
        TOKEN: ${{ secrets.TOKEN }}

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add json/all_card_ids.json

        # Проверка наличия изменений перед коммитом
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update all_card_ids.json"
          git push https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/KOTBCTAKAHE/Hamster-Kombat-API.git
        fi
